import type { Locale } from '../../app/types';

const copy = {
  en: {
    courseContents: 'Course contents',
    closeCourse: 'Close course contents',
    openCourse: 'Open course contents',
    verified: 'verified',
    verifiedLessons: 'verified lessons',
    stepOf: (step: number, total: number) => `Step ${step} of ${total}`,
    plainLanguage: 'In plain language',
    lookHere: 'Look here',
    focusOn: (name: string) => `Focus on ${name}.`,
    followPath: (from: string, to: string) => `Follow the highlighted path: ${from} → ${to}.`,
    whatChanged: 'What is true now',
    whyItHappened: 'Why this happened',
    takeaway: 'Remember this',
    previous: 'Previous',
    next: 'Next',
    replay: 'Replay step',
    restartLesson: 'Restart lesson',
    finalStepReady: 'Final step ready',
    completeLesson: 'Complete lesson',
    savingProgress: 'Saving progress…',
    savingMessage: (lessonTitle: string) =>
      `Saving ${lessonTitle} in this browser. You can keep navigating while this finishes.`,
    progressSaved: 'Progress saved',
    saveFailed: 'Progress was not saved',
    saveFailedMessage:
      'Your completion is kept for this session, but may be lost if you reload. Check browser storage access, then retry.',
    backgroundSaveFailed: (lessonTitle: string) =>
      `${lessonTitle} was not saved and may be lost if you reload.`,
    retrySave: 'Retry save',
    retrySaveFor: (lessonTitle: string) => `Retry saving ${lessonTitle}`,
    completionPrompt: (lessonTitle: string) =>
      `Complete ${lessonTitle} to save it in your learning progress.`,
    lessonComplete: 'Lesson complete',
    completionMessage: (lessonTitle: string) =>
      `You finished ${lessonTitle}. Your progress has been saved in this browser.`,
    nextLesson: (lessonTitle: string) => `Next lesson: ${lessonTitle}`,
    exploreNext: 'Explore the verified world',
    backHome: 'Back to home',
    resetCamera: 'Reset camera',
    language: 'Lesson language',
    timeline: 'Lesson step timeline',
    goToStep: (step: number, title: string) => `Go to step ${step}: ${title}`,
    legend: 'Scene legend',
    applicationTraffic: 'Blue solid — real application request',
    apiControl: 'Purple dashed — Kubernetes control command',
    scheduling: 'Amber dashed — choose a Node for a Pod',
    localNodeRuntime: 'Green short-dash — work inside one Node',
    dnsLookup: 'Teal dashed — DNS name lookup',
    storagePath: 'Green solid — storage read / write',
    ownership: 'Thin violet — who manages whom',
    placementRelation: 'Thin blue — this Pod is assigned to this Node',
    endpointMembership: 'Thin green — this backend is in the endpoint set',
    configurationLink: 'Thin gold dashed — configuration points here',
    details: 'Lesson details',
    closeDetails: 'Close lesson details',
    inspector: 'Inspector',
    terms: 'Terms',
    sources: 'Sources',
    noSelection: 'Select an object in the scene to inspect its current facts.',
    showTeaching: 'Show teaching details',
    hideTeaching: 'Collapse teaching details',
    teaching: 'Teaching explanation',
    containerRestart: 'Container restart',
    podReplacement: 'Pod replacement',
    scene: 'Interactive Kubernetes teaching scene',
    conceptual: 'Conceptual synthetic state — not live telemetry',
  },
  ja: {
    courseContents: 'コース一覧',
    closeCourse: 'コース一覧を閉じる',
    openCourse: 'コース一覧を開く',
    verified: '検証済み',
    verifiedLessons: '検証済みレッスン',
    stepOf: (step: number, total: number) => `ステップ ${step} / ${total}`,
    plainLanguage: 'まず一言で',
    lookHere: 'ここだけ見る',
    focusOn: (name: string) => `${name} に注目します。`,
    followPath: (from: string, to: string) => `強調された経路だけ追います：${from} → ${to}。`,
    whatChanged: '今どうなっているか',
    whyItHappened: 'なぜそうなったか',
    takeaway: 'これだけ覚える',
    previous: '前へ',
    next: '次へ',
    replay: 'ステップを再生',
    restartLesson: 'レッスンを最初から見る',
    finalStepReady: '最終ステップ',
    completeLesson: 'レッスンを完了',
    savingProgress: '進捗を保存中…',
    savingMessage: (lessonTitle: string) =>
      `${lessonTitle} をこのブラウザーに保存しています。保存中も移動できます。`,
    progressSaved: '進捗を保存しました',
    saveFailed: '進捗を保存できませんでした',
    saveFailedMessage:
      '完了状態はこのセッションに保持されますが、再読み込み後に失われる可能性があります。ブラウザーのストレージ設定を確認して再試行してください。',
    backgroundSaveFailed: (lessonTitle: string) =>
      `${lessonTitle} を保存できず、再読み込み後に失われる可能性があります。`,
    retrySave: '保存を再試行',
    retrySaveFor: (lessonTitle: string) => `${lessonTitle} の保存を再試行`,
    completionPrompt: (lessonTitle: string) => `${lessonTitle} を完了として学習進捗に保存します。`,
    lessonComplete: 'レッスン完了',
    completionMessage: (lessonTitle: string) =>
      `${lessonTitle} を完了しました。進捗はこのブラウザーに保存されています。`,
    nextLesson: (lessonTitle: string) => `次のレッスン: ${lessonTitle}`,
    exploreNext: '検証済み world を探索する',
    backHome: 'ホームへ戻る',
    resetCamera: 'カメラをリセット',
    language: 'レッスンの言語',
    timeline: 'レッスンのステップ',
    goToStep: (step: number, title: string) => `ステップ ${step} へ移動: ${title}`,
    legend: 'シーン凡例',
    applicationTraffic: '青い実線 — 実際のアプリ通信',
    apiControl: '紫の破線 — Kubernetes の制御命令',
    scheduling: 'オレンジ破線 — Pod を置く Node の決定',
    localNodeRuntime: '緑の短破線 — 1つの Node 内の処理',
    dnsLookup: '青緑の破線 — DNS 名前解決',
    storagePath: '緑の実線 — ストレージ読み書き',
    ownership: '細い紫線 — 誰が誰を管理するか',
    placementRelation: '細い青線 — この Pod がこの Node に配置されている',
    endpointMembership: '細い緑線 — この backend が endpoint 集合に入っている',
    configurationLink: '細い金色破線 — 設定がここを参照する',
    details: 'レッスン詳細',
    closeDetails: 'レッスン詳細を閉じる',
    inspector: 'インスペクター',
    terms: '用語',
    sources: '出典',
    noSelection: '現在の事実を確認するには、シーン内のオブジェクトを選択してください。',
    showTeaching: '解説の詳細を表示',
    hideTeaching: '解説の詳細を折りたたむ',
    teaching: '学習解説',
    containerRestart: 'Container の再起動',
    podReplacement: 'Pod の置き換え',
    scene: 'Kubernetes 学習シーン',
    conceptual: '概念用の合成状態 — ライブテレメトリではありません',
  },
  'zh-CN': {
    courseContents: '课程目录',
    closeCourse: '关闭课程目录',
    openCourse: '打开课程目录',
    verified: '已验证',
    verifiedLessons: '已验证课程',
    stepOf: (step: number, total: number) => `第 ${step} 步，共 ${total} 步`,
    plainLanguage: '先用一句人话说清楚',
    lookHere: '这一幕只看这里',
    focusOn: (name: string) => `先只看 ${name}。`,
    followPath: (from: string, to: string) => `只跟着高亮线看：${from} → ${to}。`,
    whatChanged: '现在是什么状态',
    whyItHappened: '为什么会这样',
    takeaway: '这一幕只要记住',
    previous: '上一步',
    next: '下一步',
    replay: '重播本步',
    restartLesson: '重新开始课程',
    finalStepReady: '已到最后一步',
    completeLesson: '完成课程',
    savingProgress: '正在保存进度…',
    savingMessage: (lessonTitle: string) =>
      `正在将《${lessonTitle}》保存到此浏览器，保存期间仍可继续导航。`,
    progressSaved: '进度已保存',
    saveFailed: '进度未能保存',
    saveFailedMessage:
      '本次完成状态会在当前会话中保留，但重新加载后可能丢失。请检查浏览器存储权限后重试。',
    backgroundSaveFailed: (lessonTitle: string) =>
      `《${lessonTitle}》未能保存，重新加载后可能丢失。`,
    retrySave: '重试保存',
    retrySaveFor: (lessonTitle: string) => `重试保存《${lessonTitle}》`,
    completionPrompt: (lessonTitle: string) => `将《${lessonTitle}》标记为已完成并保存到学习进度。`,
    lessonComplete: '课程已完成',
    completionMessage: (lessonTitle: string) =>
      `你已完成《${lessonTitle}》，学习进度已保存在此浏览器中。`,
    nextLesson: (lessonTitle: string) => `下一课：${lessonTitle}`,
    exploreNext: '探索已验证世界',
    backHome: '返回首页',
    resetCamera: '重置相机',
    language: '课程语言',
    timeline: '课程步骤时间线',
    goToStep: (step: number, title: string) => `跳到第 ${step} 步：${title}`,
    legend: '场景图例',
    applicationTraffic: '蓝色实线 — 真实应用请求',
    apiControl: '紫色虚线 — Kubernetes 控制命令',
    scheduling: '橙色虚线 — 决定 Pod 放到哪个 Node',
    localNodeRuntime: '绿色短虚线 — 同一 Node 内部执行',
    dnsLookup: '青色虚线 — DNS 名字解析',
    storagePath: '绿色实线 — 存储读写',
    ownership: '细紫线 — 谁管理谁',
    placementRelation: '细蓝线 — 这个 Pod 被放在这个 Node',
    endpointMembership: '细绿线 — 这个后端属于当前 Endpoint 集合',
    configurationLink: '细金色虚线 — 配置指向这里',
    details: '课程详情',
    closeDetails: '关闭课程详情',
    inspector: '对象检查器',
    terms: '术语',
    sources: '来源',
    noSelection: '请选择场景中的对象，以查看它当前的事实状态。',
    showTeaching: '展开教学详情',
    hideTeaching: '收起教学详情',
    teaching: '教学讲解',
    containerRestart: 'Container 原地重启',
    podReplacement: 'Pod 替换',
    scene: 'Kubernetes 交互教学场景',
    conceptual: '概念性合成状态 — 并非实时遥测',
  },
} as const;

export const lessonUi = (locale: Locale) => copy[locale];
