import type { Locale } from '../../app/types';

const copy = {
  en: {
    courseContents: 'Course contents',
    closeCourse: 'Close course contents',
    openCourse: 'Open course contents',
    verified: 'verified',
    verifiedLessons: 'verified lessons',
    stepOf: (step: number, total: number) => `Step ${step} of ${total}`,
    whatChanged: 'What changed',
    whyItHappened: 'Why it happened',
    takeaway: 'Takeaway',
    previous: 'Previous',
    next: 'Next',
    replay: 'Replay step',
    resetCamera: 'Reset camera',
    language: 'Lesson language',
    timeline: 'Lesson step timeline',
    goToStep: (step: number, title: string) => `Go to step ${step}: ${title}`,
    legend: 'Scene legend',
    applicationTraffic: 'Application traffic',
    apiControl: 'Kubernetes API / control',
    scheduling: 'Scheduling decision',
    ownership: 'Ownership',
    details: 'Lesson details',
    closeDetails: 'Close lesson details',
    inspector: 'Inspector',
    terms: 'Terms',
    sources: 'Sources',
    noSelection: 'Select an object in the scene to inspect its current facts.',
    showTeaching: 'Show teaching details',
    hideTeaching: 'Collapse teaching details',
    teaching: 'Teaching explanation',
    containerRestart: 'Container restart',
    podReplacement: 'Pod replacement',
    scene: 'Interactive Kubernetes teaching scene',
    conceptual: 'Conceptual synthetic state — not live telemetry',
  },
  ja: {
    courseContents: 'コース一覧',
    closeCourse: 'コース一覧を閉じる',
    openCourse: 'コース一覧を開く',
    verified: '検証済み',
    verifiedLessons: '検証済みレッスン',
    stepOf: (step: number, total: number) => `ステップ ${step} / ${total}`,
    whatChanged: '何が変わったか',
    whyItHappened: 'なぜ起きたか',
    takeaway: '要点',
    previous: '前へ',
    next: '次へ',
    replay: 'ステップを再生',
    resetCamera: 'カメラをリセット',
    language: 'レッスンの言語',
    timeline: 'レッスンのステップ',
    goToStep: (step: number, title: string) => `ステップ ${step} へ移動: ${title}`,
    legend: 'シーン凡例',
    applicationTraffic: 'アプリ通信',
    apiControl: 'Kubernetes API / 制御',
    scheduling: 'スケジューリング',
    ownership: '所有関係',
    details: 'レッスン詳細',
    closeDetails: 'レッスン詳細を閉じる',
    inspector: 'インスペクター',
    terms: '用語',
    sources: '出典',
    noSelection: '現在の事実を確認するには、シーン内のオブジェクトを選択してください。',
    showTeaching: '解説の詳細を表示',
    hideTeaching: '解説の詳細を折りたたむ',
    teaching: '学習解説',
    containerRestart: 'Container の再起動',
    podReplacement: 'Pod の置き換え',
    scene: 'Kubernetes 学習シーン',
    conceptual: '概念用の合成状態 — ライブテレメトリではありません',
  },
  'zh-CN': {
    courseContents: '课程目录',
    closeCourse: '关闭课程目录',
    openCourse: '打开课程目录',
    verified: '已验证',
    verifiedLessons: '已验证课程',
    stepOf: (step: number, total: number) => `第 ${step} 步，共 ${total} 步`,
    whatChanged: '发生了什么变化',
    whyItHappened: '为什么会发生',
    takeaway: '关键结论',
    previous: '上一步',
    next: '下一步',
    replay: '重播本步',
    resetCamera: '重置相机',
    language: '课程语言',
    timeline: '课程步骤时间线',
    goToStep: (step: number, title: string) => `跳到第 ${step} 步：${title}`,
    legend: '场景图例',
    applicationTraffic: '应用流量',
    apiControl: 'Kubernetes API / 控制流',
    scheduling: '调度决策',
    ownership: '所有关系',
    details: '课程详情',
    closeDetails: '关闭课程详情',
    inspector: '对象检查器',
    terms: '术语',
    sources: '来源',
    noSelection: '请选择场景中的对象，以查看它当前的事实状态。',
    showTeaching: '展开教学详情',
    hideTeaching: '收起教学详情',
    teaching: '教学讲解',
    containerRestart: 'Container 原地重启',
    podReplacement: 'Pod 替换',
    scene: 'Kubernetes 交互教学场景',
    conceptual: '概念性合成状态 — 并非实时遥测',
  },
} as const;

export const lessonUi = (locale: Locale) => copy[locale];
