// Generated by pnpm content:index
export const lessonFiles = [
  'cluster-overview.yaml',
  'container-restart-vs-pod-replacement.yaml',
  'manifest-to-running-pod.yaml',
  'pod-and-placement.yaml',
  'service-routes-to-pods.yaml',
] as const;
export const scenarioFiles = [
  'container-restart-golden.yaml',
  'demo-shop.yaml',
  'service-routes-to-pods.yaml',
] as const;
