import { DESKTOP_SCENE_DENSITY_BUDGET, MOBILE_SCENE_DENSITY_BUDGET } from './SceneDensityBudget';
import type { SceneGrammar } from './SceneGrammar';

export const controlFlowGrammar = Object.freeze({
  id: 'control-flow',
  purpose: 'One API-mediated causal chain from an actor to a focused workload.',
  allowedEntityKinds: [
    'Developer',
    'Kubectl',
    'KubeAPIServer',
    'Etcd',
    'ControllerManager',
    'Scheduler',
    'MetricSource',
    'HorizontalPodAutoscaler',
    'EndpointSlice',
    'Kubelet',
    'ContainerRuntime',
    'Node',
    'Deployment',
    'ReplicaSet',
    'Pod',
    'Container',
  ],
  defaultHiddenEntityKinds: ['Deployment'],
  primaryEntityKinds: [
    'Developer',
    'Kubectl',
    'KubeAPIServer',
    'Etcd',
    'ControllerManager',
    'Scheduler',
    'MetricSource',
    'HorizontalPodAutoscaler',
    'Deployment',
    'ReplicaSet',
    'Pod',
    'Container',
  ],
  entityKindPriority: [
    'Kubectl',
    'Developer',
    'KubeAPIServer',
    'Etcd',
    'ControllerManager',
    'Scheduler',
    'MetricSource',
    'HorizontalPodAutoscaler',
    'EndpointSlice',
    'ReplicaSet',
    'Deployment',
    'Pod',
    'Container',
    'Kubelet',
    'ContainerRuntime',
    'Node',
  ],
  maxVisibleByKind: {
    Developer: 1,
    Kubectl: 1,
    KubeAPIServer: 1,
    Etcd: 1,
    ControllerManager: 1,
    Scheduler: 1,
    MetricSource: 1,
    HorizontalPodAutoscaler: 1,
    EndpointSlice: 1,
    Kubelet: 1,
    ContainerRuntime: 1,
    Node: 2,
    Deployment: 1,
    ReplicaSet: 1,
    Pod: 4,
    Container: 4,
  },
  allowedRelationSemantics: [
    'control-observation',
    'endpoint-membership',
    'ownership',
    'placement',
    'composition',
  ],
  defaultHiddenRelationSemantics: ['composition'],
  relationFamilyPriority: [
    'control-observation',
    'endpoint-membership',
    'ownership',
    'placement',
    'composition',
  ],
  zones: [
    { id: 'external-actor', allowedKinds: ['Developer', 'Kubectl'] },
    {
      id: 'api-control-plane',
      allowedKinds: [
        'KubeAPIServer',
        'Etcd',
        'ControllerManager',
        'Scheduler',
        'MetricSource',
        'HorizontalPodAutoscaler',
        'EndpointSlice',
      ],
    },
    {
      id: 'focused-runtime',
      allowedKinds: [
        'Node',
        'Kubelet',
        'ContainerRuntime',
        'Deployment',
        'ReplicaSet',
        'Pod',
        'Container',
      ],
    },
  ],
  layoutAlgorithm: 'api-causality',
  cameraType: 'orthographic-isometric',
  routeRules: {
    allowedSemantics: ['control', 'scheduling', 'node-runtime'],
    requirePersistentRoute: true,
    routeParticipantsHavePriority: true,
  },
  aggregation: { aggregateKinds: ['Pod', 'Node'], mobileAggregateKinds: ['Pod', 'Node'] },
  separation: { horizontalClearance: 0.75, labelClearance: 12 },
  budgets: {
    desktop: {
      ...DESKTOP_SCENE_DENSITY_BUDGET,
      maxPrimaryEntities: 9,
      maxSecondaryEntities: 4,
      maxAnimatedTokens: 3,
    },
    mobile: {
      ...MOBILE_SCENE_DENSITY_BUDGET,
      maxPrimaryEntities: 7,
      // Node + kubelet + runtime are three distinct secondary actors in a truthful startup story.
      maxSecondaryEntities: 3,
      // A single causal story can legitimately span actor -> API -> controller/runtime. Keep all
      // persistent hops on mobile while remaining within the shared three-token ceiling.
      maxAnimatedTokens: 3,
    },
  },
} satisfies SceneGrammar);
