import { DESKTOP_SCENE_DENSITY_BUDGET, MOBILE_SCENE_DENSITY_BUDGET } from './SceneDensityBudget';
import type { SceneGrammar } from './SceneGrammar';

export const controlFlowGrammar = Object.freeze({
  id: 'control-flow',
  purpose: 'One API-mediated causal chain from an actor to a focused workload.',
  allowedEntityKinds: [
    'Developer',
    'Kubectl',
    'KubeAPIServer',
    'Etcd',
    'ControllerManager',
    'Scheduler',
    'Kubelet',
    'ContainerRuntime',
    'Node',
    'Deployment',
    'ReplicaSet',
    'Pod',
    'Container',
  ],
  defaultHiddenEntityKinds: ['Deployment'],
  primaryEntityKinds: [
    'Developer',
    'Kubectl',
    'KubeAPIServer',
    'Etcd',
    'ControllerManager',
    'Scheduler',
    'Deployment',
    'ReplicaSet',
    'Pod',
    'Container',
  ],
  entityKindPriority: [
    'Kubectl',
    'Developer',
    'KubeAPIServer',
    'Etcd',
    'ControllerManager',
    'Scheduler',
    'ReplicaSet',
    'Deployment',
    'Pod',
    'Container',
    'Kubelet',
    'ContainerRuntime',
    'Node',
  ],
  maxVisibleByKind: {
    Developer: 1,
    Kubectl: 1,
    KubeAPIServer: 1,
    Etcd: 1,
    ControllerManager: 1,
    Scheduler: 1,
    Kubelet: 1,
    ContainerRuntime: 1,
    Node: 2,
    Deployment: 1,
    ReplicaSet: 1,
    Pod: 4,
    Container: 4,
  },
  allowedRelationSemantics: ['control-observation', 'ownership', 'placement', 'composition'],
  defaultHiddenRelationSemantics: ['composition'],
  relationFamilyPriority: ['control-observation', 'ownership', 'placement', 'composition'],
  zones: [
    { id: 'external-actor', allowedKinds: ['Developer', 'Kubectl'] },
    {
      id: 'api-control-plane',
      allowedKinds: ['KubeAPIServer', 'Etcd', 'ControllerManager', 'Scheduler'],
    },
    {
      id: 'focused-runtime',
      allowedKinds: [
        'Node',
        'Kubelet',
        'ContainerRuntime',
        'Deployment',
        'ReplicaSet',
        'Pod',
        'Container',
      ],
    },
  ],
  layoutAlgorithm: 'api-causality',
  cameraType: 'orthographic-isometric',
  routeRules: {
    allowedSemantics: ['control', 'scheduling', 'node-runtime'],
    requirePersistentRoute: true,
    routeParticipantsHavePriority: true,
  },
  aggregation: { aggregateKinds: ['Pod', 'Node'], mobileAggregateKinds: ['Pod', 'Node'] },
  separation: { horizontalClearance: 0.75, labelClearance: 12 },
  budgets: {
    desktop: {
      ...DESKTOP_SCENE_DENSITY_BUDGET,
      maxPrimaryEntities: 9,
      maxSecondaryEntities: 4,
      maxAnimatedTokens: 3,
    },
    mobile: {
      ...MOBILE_SCENE_DENSITY_BUDGET,
      maxPrimaryEntities: 7,
      maxSecondaryEntities: 2,
      maxAnimatedTokens: 2,
    },
  },
} satisfies SceneGrammar);
