import { DESKTOP_SCENE_DENSITY_BUDGET, MOBILE_SCENE_DENSITY_BUDGET } from './SceneDensityBudget';
import type { SceneGrammar } from './SceneGrammar';

export const overviewGrammar = Object.freeze({
  id: 'overview',
  purpose: 'Cluster boundary, control plane, worker Nodes, and representative Pods.',
  allowedEntityKinds: [
    'Cluster',
    'KubeAPIServer',
    'Etcd',
    'Scheduler',
    'ControllerManager',
    'Node',
    'Pod',
    'Kubelet',
    'ContainerRuntime',
    'Developer',
  ],
  defaultHiddenEntityKinds: ['Kubelet', 'ContainerRuntime', 'Developer'],
  primaryEntityKinds: [
    'Cluster',
    'KubeAPIServer',
    'Etcd',
    'Scheduler',
    'ControllerManager',
    'Node',
  ],
  entityKindPriority: [
    'Cluster',
    'KubeAPIServer',
    'Etcd',
    'Scheduler',
    'ControllerManager',
    'Node',
    'Pod',
    'Developer',
    'Kubelet',
    'ContainerRuntime',
  ],
  maxVisibleByKind: {
    Cluster: 1,
    KubeAPIServer: 1,
    Etcd: 1,
    Scheduler: 1,
    ControllerManager: 1,
    Node: 3,
    Pod: 4,
    Developer: 1,
  },
  allowedRelationSemantics: ['control-observation', 'placement'],
  defaultHiddenRelationSemantics: [],
  relationFamilyPriority: ['control-observation', 'placement'],
  zones: [
    {
      id: 'control-plane-island',
      allowedKinds: ['KubeAPIServer', 'Etcd', 'Scheduler', 'ControllerManager'],
    },
    { id: 'worker-nodes-island', allowedKinds: ['Node', 'Pod', 'Kubelet', 'ContainerRuntime'] },
    { id: 'external-entry', allowedKinds: ['Developer'] },
  ],
  layoutAlgorithm: 'foundation-islands',
  cameraType: 'orthographic-isometric',
  routeRules: {
    allowedSemantics: ['control', 'scheduling'],
    requirePersistentRoute: true,
    routeParticipantsHavePriority: true,
  },
  aggregation: { aggregateKinds: ['Pod'], mobileAggregateKinds: ['Pod', 'Node'] },
  separation: { horizontalClearance: 0.7, labelClearance: 10 },
  budgets: {
    desktop: {
      ...DESKTOP_SCENE_DENSITY_BUDGET,
      maxPrimaryEntities: 9,
      maxSecondaryEntities: 4,
      maxRelationLabels: 1,
      maxFocusedEntities: 2,
      maxAnimatedTokens: 2,
    },
    mobile: {
      ...MOBILE_SCENE_DENSITY_BUDGET,
      maxPrimaryEntities: 7,
      maxSecondaryEntities: 1,
      maxAnimatedTokens: 1,
    },
  },
} satisfies SceneGrammar);
