import type { RelationSemantic } from '../../world/types';
import type {
  ContextRelationStyle,
  RelationEmphasis,
  RouteSemantic,
  TeachingRouteStyle,
  WideLineStyle,
} from './relationTypes';

const colors = Object.freeze({
  neutral: 0x8aa0b6,
  placement: 0x6d9fc8,
  control: 0x9b87f5,
  scheduling: 0xf4aa3c,
  dataFlow: 0x35bdf6,
  dns: 0x2dd4bf,
  endpoint: 0x43c69a,
  storage: 0x43c69a,
  configuration: 0xb3a56e,
});

const context = (
  semantic: RelationSemantic,
  style: Omit<ContextRelationStyle, 'semantic'>,
): ContextRelationStyle => Object.freeze({ semantic, ...style });

const CONTEXT_STYLES: Readonly<Record<RelationSemantic, ContextRelationStyle>> = Object.freeze({
  ownership: context('ownership', {
    color: colors.control,
    widthCssPx: 1.75,
    opacity: 0.66,
    dashed: false,
    dashSize: 0,
    gapSize: 0,
    dashScale: 1,
    arrowhead: true,
    chevrons: false,
    curve: 'bezier',
    elevation: 0.16,
    renderOrder: 4,
    labelMode: 'on-focus',
    externalLine: true,
  }),
  scope: context('scope', {
    color: colors.neutral,
    widthCssPx: 1.5,
    opacity: 0.4,
    dashed: true,
    dashSize: 0.24,
    gapSize: 0.18,
    dashScale: 1,
    arrowhead: false,
    chevrons: false,
    curve: 'bezier',
    elevation: 0.12,
    renderOrder: 2,
    labelMode: 'none',
    externalLine: true,
  }),
  placement: context('placement', {
    color: colors.placement,
    widthCssPx: 1.6,
    opacity: 0.62,
    dashed: false,
    dashSize: 0,
    gapSize: 0,
    dashScale: 1,
    arrowhead: true,
    chevrons: false,
    curve: 'orthogonal',
    elevation: 0.12,
    renderOrder: 3,
    labelMode: 'on-focus',
    externalLine: true,
  }),
  composition: context('composition', {
    color: colors.neutral,
    widthCssPx: 1.5,
    opacity: 0,
    dashed: false,
    dashSize: 0,
    gapSize: 0,
    dashScale: 1,
    arrowhead: false,
    chevrons: false,
    curve: 'straight',
    elevation: 0,
    renderOrder: 0,
    labelMode: 'none',
    externalLine: false,
  }),
  'control-observation': context('control-observation', {
    color: colors.control,
    widthCssPx: 2,
    opacity: 0.72,
    dashed: true,
    dashSize: 0.34,
    gapSize: 0.22,
    dashScale: 1,
    arrowhead: true,
    chevrons: false,
    curve: 'orthogonal',
    elevation: 0.28,
    renderOrder: 5,
    labelMode: 'on-focus',
    externalLine: true,
  }),
  selection: context('selection', {
    color: colors.endpoint,
    widthCssPx: 1.75,
    opacity: 0.64,
    dashed: true,
    dashSize: 0.25,
    gapSize: 0.14,
    dashScale: 1,
    arrowhead: true,
    chevrons: false,
    curve: 'bezier',
    elevation: 0.2,
    renderOrder: 4,
    labelMode: 'on-focus',
    externalLine: true,
  }),
  'endpoint-membership': context('endpoint-membership', {
    color: colors.endpoint,
    widthCssPx: 1.75,
    opacity: 0.72,
    dashed: false,
    dashSize: 0,
    gapSize: 0,
    dashScale: 1,
    arrowhead: true,
    chevrons: false,
    curve: 'bezier',
    elevation: 0.18,
    renderOrder: 4,
    labelMode: 'on-focus',
    externalLine: true,
  }),
  'data-flow': context('data-flow', {
    color: colors.dataFlow,
    widthCssPx: 2.25,
    opacity: 0.78,
    dashed: false,
    dashSize: 0,
    gapSize: 0,
    dashScale: 1,
    arrowhead: true,
    chevrons: true,
    curve: 'bezier',
    elevation: 0.3,
    renderOrder: 5,
    labelMode: 'on-focus',
    externalLine: true,
  }),
  'DNS-flow': context('DNS-flow', {
    color: colors.dns,
    widthCssPx: 2,
    opacity: 0.76,
    dashed: true,
    dashSize: 0.38,
    gapSize: 0.18,
    dashScale: 1,
    arrowhead: true,
    chevrons: false,
    curve: 'bezier',
    elevation: 0.3,
    renderOrder: 5,
    labelMode: 'on-focus',
    externalLine: true,
  }),
  storage: context('storage', {
    color: colors.storage,
    widthCssPx: 2.25,
    opacity: 0.76,
    dashed: false,
    dashSize: 0,
    gapSize: 0,
    dashScale: 1,
    arrowhead: true,
    chevrons: false,
    curve: 'orthogonal',
    elevation: 0.22,
    renderOrder: 4,
    labelMode: 'on-focus',
    externalLine: true,
  }),
  configuration: context('configuration', {
    color: colors.configuration,
    widthCssPx: 1.5,
    opacity: 0.52,
    dashed: true,
    dashSize: 0.2,
    gapSize: 0.18,
    dashScale: 1,
    arrowhead: true,
    chevrons: false,
    curve: 'orthogonal',
    elevation: 0.18,
    renderOrder: 3,
    labelMode: 'on-focus',
    externalLine: true,
  }),
});

const route = (
  semantic: RouteSemantic,
  style: Omit<TeachingRouteStyle, 'semantic'>,
): TeachingRouteStyle => Object.freeze({ semantic, ...style });

const ACTIVE_ROUTE_STYLES: Readonly<Record<RouteSemantic, TeachingRouteStyle>> = Object.freeze({
  control: route('control', {
    color: colors.control,
    tokenColor: 0xc8bcff,
    tokenCount: 1,
    widthCssPx: 4.5,
    opacity: 0.98,
    dashed: true,
    dashSize: 0.42,
    gapSize: 0.24,
    dashScale: 1,
    arrowhead: true,
    chevrons: false,
    curve: 'orthogonal',
    elevation: 0.42,
    renderOrder: 20,
    labelMode: 'always',
  }),
  scheduling: route('scheduling', {
    color: colors.scheduling,
    tokenColor: 0xffd27a,
    tokenCount: 1,
    widthCssPx: 5,
    opacity: 1,
    dashed: false,
    dashSize: 0,
    gapSize: 0,
    dashScale: 1,
    arrowhead: true,
    chevrons: true,
    curve: 'orthogonal',
    elevation: 0.46,
    renderOrder: 22,
    labelMode: 'always',
  }),
  'data-flow': route('data-flow', {
    color: colors.dataFlow,
    tokenColor: 0xa6e6ff,
    tokenCount: 2,
    widthCssPx: 5.5,
    opacity: 1,
    dashed: false,
    dashSize: 0,
    gapSize: 0,
    dashScale: 1,
    arrowhead: true,
    chevrons: true,
    curve: 'bezier',
    elevation: 0.5,
    renderOrder: 24,
    labelMode: 'always',
  }),
  dns: route('dns', {
    color: colors.dns,
    tokenColor: 0x99f6e4,
    tokenCount: 1,
    widthCssPx: 4.5,
    opacity: 0.98,
    dashed: true,
    dashSize: 0.48,
    gapSize: 0.2,
    dashScale: 1,
    arrowhead: true,
    chevrons: false,
    curve: 'bezier',
    elevation: 0.5,
    renderOrder: 22,
    labelMode: 'always',
  }),
});

const opacityFactor = (emphasis: RelationEmphasis): number => {
  if (emphasis === 'dimmed') return 0.24;
  if (emphasis === 'focused') return 1.12;
  if (emphasis === 'active') return 1.2;
  return 1;
};

const widthFactor = (emphasis: RelationEmphasis): number => {
  if (emphasis === 'focused') return 1.2;
  if (emphasis === 'active') return 1.35;
  return 1;
};

export const getContextRelationStyle = (
  semantic: RelationSemantic,
  emphasis: RelationEmphasis = 'normal',
): ContextRelationStyle => {
  const base = CONTEXT_STYLES[semantic];
  return Object.freeze({
    ...base,
    widthCssPx: base.widthCssPx * widthFactor(emphasis),
    opacity: Math.min(1, base.opacity * opacityFactor(emphasis)),
  });
};

export const getTeachingRouteStyle = (semantic: RouteSemantic): TeachingRouteStyle =>
  ACTIVE_ROUTE_STYLES[semantic];

export const isActiveRouteWidth = (style: WideLineStyle): boolean => style.widthCssPx >= 4;

export const relationLegendStyles = Object.freeze({
  application: ACTIVE_ROUTE_STYLES['data-flow'],
  control: ACTIVE_ROUTE_STYLES.control,
  scheduling: ACTIVE_ROUTE_STYLES.scheduling,
  ownership: CONTEXT_STYLES.ownership,
});
