import { readdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const lessonDirectory = resolve(root, 'content/courses/kubernetes-foundations/lessons');
const lessons = readdirSync(lessonDirectory)
  .filter((file) => file.endsWith('.yaml'))
  .sort();
const output = `// Generated by pnpm content:index\nexport const lessonFiles = ${JSON.stringify(lessons, null, 2)} as const;\n`;
writeFileSync(resolve(root, 'src/content/generated-index.ts'), output, 'utf8');
console.log(`Generated index for ${lessons.length} lessons.`);
